# 应用服务 WEB 访问端口
server:
  port: 8089

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///flowable?serverTimezone=Asia/Shanghai&useSSL=false

flowable:
  activity-font-name: "宋体"
  label-font-name: "宋体"
  annotation-font-name: "宋体"